version: "3"
services:
    sinatra:
        image: sinatra_flask
        container_name: sin_flask
        ports: 
            - "5000:5000"
        environment:
            - FLASK_APP=application.py
            - FLASK_DEBUG=1